name: doctor_app
description: Doctor-facing native Flutter app for Lokal MedAssist.
publish_to: none
version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  lokal_health_shared:
    path: ../../packages/lokal_health_shared
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

flutter:
  uses-material-design: true
